-- Columns required by JPA entities (validate mode) beyond V1

ALTER TABLE product
    ADD COLUMN IF NOT EXISTS popularity_score INT NOT NULL DEFAULT 0;

ALTER TABLE product_listing
    ADD COLUMN IF NOT EXISTS trust_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS is_fake_promo BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS crawl_time TIMESTAMP;
