export type RawProductDetail = {
  url: string;
  name: string | null;
  brandName: string | null;
  barcode: string | null;
  statusText: string | null;
  inStock: boolean | null;
  remainingQuantityText: string | null;
  branchesInStockText: string | null;
  price: number | null;
  originalPrice: number | null;
  flashSalePrice: number | null;
  discountPct: number | null;
  description: string | null;
  benefits: string | null;
  usage: string | null;
  ingredients: string | null;
  breadcrumb: string[];
  galleryImages: string[];
  crawledAt: string;
};
